name: CI/CD
on:
     push:
            branches:
                - master
                - main
     pull_request:
        branches:
             - master
             - main

jobs:
    test:
        runs-on: ubunto-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            - run: python test_app.py