name: CI-CD

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - run: pip install --upgrade pip && pip install -r requirements.txt
            - run: pytest
    build:
         runs-on: ubuntu-latest
         steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name : Login to github container
              uses: docker/login-action@v3
              with:
                 registery: ghcr.io
                 username: ${{ github.actor }}
                 password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              uses: docker/build-push-action@v6
              with:
                  context: F.
                  push: false
                  tags : ghcr.io/${{github.repository}}:latest
               
            
